---
name: Harness SAST/SCA/Secrets/Container Scanning 

on:
  pull_request:
  workflow_dispatch:
  push:


jobs:
  Harness-Static-Analysis:
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    #container: shiftleft/core:latest

    steps:
    - uses: actions/checkout@v4

    # - name: Set up Java
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'zulu'   # or 'zulu', 'corretto', 'microsoft', etc.
    #     java-version: '17'        # set to whatever version you need

    # - name: Verify JAVA_HOME is set
    #   shell: cmd
    #   run: |
    #     echo %JAVA_HOME%
    #     java -version

    - name: Download ShiftLeft CLI1
      shell: pwsh
      run: | 
        #Invoke-WebRequest -Uri https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip -UseBasicParsing -OutFile sl-latest-windows-x64.zip
        Expand-Archive -Path sl-0.9.4424-windows-x64.zip -DestinationPath .
     
  #   # - name: Download Harness CLI
  #   #   run: |
  #   #     curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ${GITHUB_WORKSPACE}/sl 

    - name: Run Harness Scan
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/sl analyze --groovy --tag branch=${{ github.head_ref }} --verbose --wait --app "${GITHUB_REPOSITORY#*/}" .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

  # Build-Rules:
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   needs: Harness-Static-Analysis
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Download ShiftLeft CLI
  #     run: |
  #       curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
  #   - name: Run check-analysis
  #     shell: bash
  #     continue-on-error: false
  #     run: |
  #       ${GITHUB_WORKSPACE}/sl check-analysis --v2 --multilanguage --verbose --app "${GITHUB_REPOSITORY#*/}" \
  #           --report-file qwietreport.md --config shiftleft.yml \
  #           --github-pr-number=${{github.event.number}} \
  #           --github-pr-user=${{ github.repository_owner }} \
  #           --github-pr-repo=${{ github.event.repository.name }} \
  #           --github-token=${{ secrets.GITHUB_TOKEN }}
  #     env:
  #       SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}   
     

      



 
